#!/usr/bin/env python
import sys

from javaclass.classfile import ClassFile

if __name__ == "__main__":
    f = open(sys.argv[1], "rb")
    in_data = f.read()
    c = ClassFile(in_data)
    f.close()
    print c.dump()
